DELETE http://localhost:8080/book/2

###
PUT http://localhost:8080/book
Content-Type: application/json

{
  "id": 1,
  "name": "Java 8 Programming",
  "price": 50.00
}

###
GET http://localhost:8080/books
Accept: application/json

###
POST http://localhost:8080/book
Content-Type: application/json

{
  "name": "Scala Programming",
  "price": 40.45
}

###
